services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_consistent_hash_exchange &&
               rabbitmq-server "

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: -js

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs
      AWS_DEFAULT_REGION: us-east-1
