name = "shove-docs"
compatibility_date = "2026-04-27"

[assets]
directory = "./docs/dist"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1